<?php

/** Generated by Latte 3.0.23 */

use Latte\Runtime as LR;

/** source: /private/var/www/basic-framework/src/TemplateEngine/Templates/test.latte */
final class Template_cae2ca5b94 extends Latte\Runtime\Template
{
	public const Source = '/private/var/www/basic-framework/src/TemplateEngine/Templates/test.latte';


	public function main(array $ʟ_args): void
	{
		echo 'herj';
	}
}
