<?php

/** Generated by Latte 3.0.23 */

use Latte\Runtime as LR;

/** source: /Users/rene/www/basic-framework/src/TemplateEngine/Templates/frontpage.latte */
final class Template_b608877048 extends Latte\Runtime\Template
{
	public const Source = '/Users/rene/www/basic-framework/src/TemplateEngine/Templates/frontpage.latte';


	public function main(array $ʟ_args): void
	{
		echo '<h2>Velkommen på forsiden...</h2>';
	}
}
