<?php

/** Generated by Latte 3.0.23 */

use Latte\Runtime as LR;

/** source: /private/var/www/basic-framework/src/Bootstrap/../TemplateEngine/Templates/frontpage.latte */
final class Template_986b9d4c81 extends Latte\Runtime\Template
{
	public const Source = '/private/var/www/basic-framework/src/Bootstrap/../TemplateEngine/Templates/frontpage.latte';


	public function main(array $ʟ_args): void
	{
		echo '<h2>Velkommen på forsiden...</h2>';
	}
}
