<?php

/** Generated by Latte 3.0.23 */

use Latte\Runtime as LR;

/** source: /private/var/www/basic-framework/src/TemplateEngine/Templates/layout.latte */
final class Template_b7eecc7e30 extends Latte\Runtime\Template
{
	public const Source = '/private/var/www/basic-framework/src/TemplateEngine/Templates/layout.latte';

	public const Blocks = [
		['content' => 'blockContent'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<!doctype html>
<html lang="da">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="description" content="Basic framework" />
  <meta name="author" content="Rene Petersen" />

  <title>Basic framework</title>
</head>
<body>
    <div id="content">
';
		$this->renderBlock('content', get_defined_vars()) /* line 13 */;
		echo '    </div>
</body>
</html>';
	}


	/** {block content} on line 13 */
	public function blockContent(array $ʟ_args): void
	{
	}
}
