<?php

/** Generated by Latte 3.0.23 */

use Latte\Runtime as LR;

/** source: /private/var/www/basic-framework/src/TemplateEngine/Templates/frontpage.latte */
final class Template_0e93f2b976 extends Latte\Runtime\Template
{
	public const Source = '/private/var/www/basic-framework/src/TemplateEngine/Templates/frontpage.latte';

	public const Blocks = [
		['content' => 'blockContent'],
	];


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo "\n";
		$this->renderBlock('content', get_defined_vars()) /* line 3 */;
	}


	public function prepare(): array
	{
		extract($this->params);

		$this->parentName = 'layout.latte';
		return get_defined_vars();
	}


	/** {block content} on line 3 */
	public function blockContent(array $ʟ_args): void
	{
		echo '    <h2>Velkommen på forsiden...</h2>';
	}
}
